import { addEditSaveFunction } from "./edit_task.js";
import { addDeleteFunction } from "./delete_task.js";
import { addStatusFunctionality } from "./mark_task_status.js";
export function createCard(id, title="", description="", completed=false){
    let container = document.createElement("div");
    container.classList.add("container");
    container.id = `container-${id}`
    let card = document.createElement("div");
    card.classList.add("card");
    card.classList.add(completed ? "task-completed": "task-pending");

    card.id = `card-${id}`;
    let title_element = document.createElement("h1");
    title_element.classList.add("task-heading", "raleway-font-bold");
    title_element.textContent = title;
    let description_element = document.createElement("p");
    description_element.classList.add("task-description", "Mukta-font-regular");
    description_element.contentEditable = false;
    description_element.textContent = description;
    let input = document.createElement("textarea");
    input.classList.add("edit-task-input", "edit-input", "hidden");
    input.dataset.taskId = id;
    input.value = description;
    let button_row = document.createElement("div");
    button_row.classList.add("button-row");
    let save_button = document.createElement("button");
    save_button.classList.add("save-button", "hidden");
    save_button.dataset.taskId = id;
    save_button.ariaLabel = "Save";
    let save_button_icon = document.createElement("i");
    save_button_icon.classList.add("fa-solid", "fa-floppy-disk");
    save_button.appendChild(save_button_icon);
    let undo_button = document.createElement("button");
    undo_button.classList.add("undo-button", "hidden");
    undo_button.dataset.taskId = id;
    undo_button.ariaLabel = "Undo";
    let undo_button_icon = document.createElement("i");
    undo_button_icon.classList.add("fa-solid", "fa-arrow-rotate-left");
    undo_button.appendChild(undo_button_icon);
    let delete_button = document.createElement("button");
    delete_button.classList.add("delete-button");
    delete_button.id = `delete-button-${id}`;
    delete_button.dataset.taskId = id;
    delete_button.ariaLabel = "Delete";
    let delete_button_icon = document.createElement("i");
    delete_button_icon.classList.add("fa-solid", "fa-trash");
    delete_button.appendChild(delete_button_icon);
    addDeleteFunction(delete_button);
    let edit_button = document.createElement("button");
    edit_button.classList.add("edit-button");
    edit_button.id = `edit-button-${id}`;
    edit_button.dataset.taskId = id;
    edit_button.ariaLabel = "Edit";
    let edit_button_icon = document.createElement("i");
    edit_button_icon.classList.add("fa-solid", "fa-pencil");
    edit_button.appendChild(edit_button_icon);
    addEditSaveFunction(edit_button, save_button, undo_button);
    let toggle_status_button = document.createElement("button");
    toggle_status_button.classList.add("toggle-status-button");
    toggle_status_button.id = `toggle-status-button-${id}`;
    toggle_status_button.dataset.taskId = id;
    toggle_status_button.ariaLabel = "Toggle Status";
    let toggle_status_button_icon = document.createElement("i");
    toggle_status_button_icon.classList.add("fa-solid", "fa-check");
    toggle_status_button.appendChild(toggle_status_button_icon);
    addStatusFunctionality(toggle_status_button);


    button_row.appendChild(undo_button);
    button_row.appendChild(save_button);
    container.appendChild(card);
    card.appendChild(title_element);
    card.appendChild(description_element);
    card.appendChild(input);
    card.appendChild(button_row);
    container.appendChild(edit_button);
    container.appendChild(delete_button);
    container.appendChild(toggle_status_button);
    return container;
}